#!/usr/bin/env bash
set -o errexit   # exit on error
set -o pipefail  # exit on error in pipes
set -o nounset   # exit on unset variable
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
cd "$ROOT_DIR"


# clean
rm -rf build
rm -rf dist
rm -rf CMakeUserPresets.json
rm -rf test_package/build
rm -rf test_package/CMakeUserPresets.json
